### ISSUE TITLE
About prompts in gpt3_prompts fold

### ISSUE THREAD

**Issue by ImageProcessing01** [vishaal27/SuS-X#2]
Dear Sir,

I find that directly encoding the released CuPL prompts in the 'gpt3_prompts' fold can not reproduce the reported result.

I wonder if you have done some selections on the CuPL prompts? because the prompt number for each category is not equal.

And thanks for your excellent work.

**Comment by vishaal27** [comment]
Hello,

Thanks for your question -- I have not done any processing/selection of the CuPL prompts. I have used them as is. Could you let me know which results you are not able to reproduce. To ease reproducibility, I also have released the weights used for each of the results here: [https://drive.google.com/drive/folders/1nzRf13Ha1gvKP_n_4a_JreplA0QkHGBh?usp=sharing](https://drive.google.com/drive/folders/1nzRf13Ha1gvKP_n_4a_JreplA0QkHGBh?usp=sharing)

Please download these, and try and match the results obtained with yours. 

Hope this helps, let me know if the issue persists!

**Comment by yangyangyang127** [comment]
Dear Sir,

Yeah, the weights can be used to reproduce the reported results and the problem has been solved.

But I still can't reproduce the results with the CuPL prompts, e.g., If I directly encode the CuPL prompts of ImageNet, I obtain the zero-shot ACC 57.+%, though this is not a problem for me now.

And thanks for your reply.

**Comment by vishaal27** [comment]
I see, interesting -- could you check with the prompts here: [https://github.com/sarahpratt/CuPL/blob/main/imagenet_prompts/CuPL_image_prompts.json](https://github.com/sarahpratt/CuPL/blob/main/imagenet_prompts/CuPL_image_prompts.json).

It is suprising that you get the same numbers with the weights but not with the CuPL prompts. Is this problem only with ImageNet? Can you please check and confirm for other datasets? Also, I presume this is with reproducing the CuPL baseline results right?

**Comment by yangyangyang127** [comment]
> I see, interesting -- could you check with the prompts here: https://github.com/sarahpratt/CuPL/blob/main/imagenet_prompts/CuPL_image_prompts.json.
> 
> It is suprising that you get the same numbers with the weights but not with the CuPL prompts. Is this problem only with ImageNet? Can you please check and confirm for other datasets? Also, I presume this is with reproducing the CuPL baseline results right?


Dear Sir,
I have checked the prompts from CuPL and I can achieve the ACC reported in the paper. I only checked the imagenet. And I do not know the results of other datasets.

I guess the problem is in the prompts. The CuPL prompt contains 50 descriptions for each category, but the SuS-released prompt contains 30 descriptions for each category. Considering that CLIP is very sensitive to prompts, I think this is the cause. 

And thanks for your patience.
