### ISSUE TITLE
About the clip-retrieval version

### ISSUE THREAD

**Issue by haoweiz23** [vishaal27/SuS-X#7]
The version of clip-retrieval seems wrong, the 'clip_client' function does not exist in clip_retrieval==2.29.1, updating the package to 2.37.0 can solve this problem.

**Comment by vishaal27** [comment]
Thanks for your interest in our work. As far as I recollect, I used the 2.29.1 version for all my experiments, but I agree that upgrading the version to the latest one from here: https://github.com/rom1504/clip-retrieval/releases would be beneficial.
